### ISSUE TITLE
API Broken?

### ISSUE THREAD

**Issue by stdscatchemall** [samuelcouch/teespring-api#9]
I hate to keep bothering you, but I'm getting this error when I try to query your API with a known existing Teespring campaign.

**Comment by stdscatchemall** [comment]
A+ github mobile... 

TypeError: Cannot read property '0' of undefined at /root/teespring-api/utils.js:42:17 at Request._callback (/root/teespring-api/utils.js:31:5) at self.callback (/root/teespring-api/node_modules/request/request.js:373:22) at Request.emit (events.js:95:17) at Request.init (/root/teespring-api/node_modules/request/request.js:387:17) at new Request (/root/teespring-api/node_modules/request/request.js:283:8) at request (/root/teespring-api/node_modules/request/index.js:50:10) at springSearch (/root/teespring-api/utils.js:26:3) at getCampaign (/root/teespring-api/utils.js:38:3) at Object.app.get.query [as handle] (/root/teespring-api/server.js:35:2)

**Comment by samuelcouch** [comment]
Looks like the request formatting changed on their end. Will look in to updating. 

Sam Couch310.913.9683

couch@temple.edu

**Comment by samuelcouch** [comment]
Just checked in to the issue, looks like the requests are getting bounced back on our end, so we can't serve anything up. In the next day or two I will publish an NPM module that you can use to host your own private instance of the API. That'll make it easier for everyone.

**Comment by samuelcouch** [comment]
Give this a look now, http://teespringfor.me/ also visit the new project samuelcouch/node-teespring

I'm encouraging others to host their own personal versions of the API

**Comment by stdscatchemall** [comment]
I will take a like look at it tomorrow! Thanks for working quickly on it :)
